### ISSUE TITLE
Run on Linux subsystem for Windows

### ISSUE THREAD

**Issue by Joelius300** [ChrisPenner/void-space#2]
I was wondering if it's possible to get this great piece of software to run on the WSL. I tried on both the normal Windows 10 (with of course didn't work because vty only supports POSIX) and on the WSL (running Debian) but I couldn't get it to work. Installing Stack worked on both but `stack build` fails on vty-5.21 - also on both.

Maybe it's obvious and I'm just not informed enough but shouldn't I be able to install it on the WSL? Is there something I need to do differently on WSL?

**Comment by richardfoy** [comment]
I had this problem on CentOS, and I found out that the problem was I needed to install `ncurses-dev`. I'm not sure how WSL handles it but I hope this helps!

**Comment by Joelius300** [comment]
It worked, thank you so much!
